AWSTemplateFormatVersion: 2010-09-09

Resources:
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.markdowntables.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: markdowntables.com
          Protocol: https

  RedirectBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RedirectBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub ${RedirectBucket.Arn}/*
